development:
  adapter: postgresql
  encoding: unicode
  database: thecolbyecho 
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PG_DB_NAME_TEST'] %> 
  pool: 5
  password:
  host: localhost
